#include "vm.h"

#include <assert.h>
#include <stdio.h>

#include "ubench.h"

UBENCH_EX(String, ManyShort) {
  VM vm;
  InterpretResult ires;
  const char src[] =
      "{ \n"
      "  var _00; var _01; var _02; var _03; var _04; \n"
      "  var _05; var _06; var _07; var _08; var _09; \n"
      "  var _10; var _11; var _12; var _13; var _14; \n"
      "  for (var i = 0; i < 32768; i = i + 1) { \n"
      "    _00 = !_00; \n"
      "    if (_00) { _01 = !_01; \n"
      "    if (_01) { _02 = !_02; \n"
      "    if (_02) { _03 = !_03; \n"
      "    if (_03) { _04 = !_04; \n"
      "    if (_04) { _05 = !_05; \n"
      "    if (_05) { _06 = !_06; \n"
      "    if (_06) { _07 = !_07; \n"
      "    if (_07) { _08 = !_08; \n"
      "    if (_08) { _09 = !_09; \n"
      "    if (_09) { _10 = !_10; \n"
      "    if (_10) { _11 = !_11; \n"
      "    if (_11) { _12 = !_12; \n"
      "    if (_12) { _13 = !_13; \n"
      "    if (_13) { _14 = !_14; \n"
      "    }}}}}}}}}}}}}} \n"
      "    var a; \n"
      "    if (_05) { \n"
      "      if (_06) { \n"
      "        if (_07) { \n"
      "          if (_08) { \n"
      "            if (_09) a = \"A\"; else a = \"a\"; \n"
      "          } else { \n"
      "            if (_09) a = \"B\"; else a = \"b\"; \n"
      "          } \n"
      "        } else { \n"
      "          if (_08) { \n"
      "            if (_09) a = \"C\"; else a = \"c\"; \n"
      "          } else { \n"
      "            if (_09) a = \"D\"; else a = \"d\"; \n"
      "          } \n"
      "        } \n"
      "      } else { \n"
      "        if (_07) { \n"
      "          if (_08) { \n"
      "            if (_09) a = \"E\"; else a = \"e\"; \n"
      "          } else { \n"
      "            if (_09) a = \"F\"; else a = \"f\"; \n"
      "          } \n"
      "        } else { \n"
      "          if (_08) { \n"
      "            if (_09) a = \"G\"; else a = \"g\"; \n"
      "          } else { \n"
      "            if (_09) a = \"H\"; else a = \"h\"; \n"
      "          } \n"
      "        } \n"
      "      } \n"
      "    } else { \n"
      "      if (_06) { \n"
      "        if (_07) { \n"
      "          if (_08) { \n"
      "            if (_09) a = \"I\"; else a = \"i\"; \n"
      "          } else { \n"
      "            if (_09) a = \"J\"; else a = \"j\"; \n"
      "          } \n"
      "        } else { \n"
      "          if (_08) { \n"
      "            if (_09) a = \"K\"; else a = \"k\"; \n"
      "          } else { \n"
      "            if (_09) a = \"L\"; else a = \"l\"; \n"
      "          } \n"
      "        } \n"
      "      } else { \n"
      "        if (_07) { \n"
      "          if (_08) { \n"
      "            if (_09) a = \"M\"; else a = \"m\"; \n"
      "          } else { \n"
      "            if (_09) a = \"N\"; else a = \"n\"; \n"
      "          } \n"
      "        } else { \n"
      "          if (_08) { \n"
      "            if (_09) a = \"O\"; else a = \"o\"; \n"
      "          } else { \n"
      "            if (_09) a = \"P\"; else a = \"p\"; \n"
      "          } \n"
      "        } \n"
      "      } \n"
      "    } \n"
      "    var b; \n"
      "    if (_10) { \n"
      "      if (_11) { \n"
      "        if (_12) { \n"
      "          if (_13) { \n"
      "            if (_14) b = \"`\"; else b = \"~\"; \n"
      "          } else { \n"
      "            if (_14) b = \"!\"; else b = \"1\"; \n"
      "          } \n"
      "        } else { \n"
      "          if (_13) { \n"
      "            if (_14) b = \"@\"; else b = \"2\"; \n"
      "          } else { \n"
      "            if (_14) b = \"#\"; else b = \"3\"; \n"
      "          } \n"
      "        } \n"
      "      } else { \n"
      "        if (_12) { \n"
      "          if (_13) { \n"
      "            if (_14) b = \"$\"; else b = \"4\"; \n"
      "          } else { \n"
      "            if (_14) b = \"%\"; else b = \"5\"; \n"
      "          } \n"
      "        } else { \n"
      "          if (_13) { \n"
      "            if (_14) b = \"^\"; else b = \"6\"; \n"
      "          } else { \n"
      "            if (_14) b = \"&\"; else b = \"7\"; \n"
      "          } \n"
      "        } \n"
      "      } \n"
      "    } else { \n"
      "      if (_11) { \n"
      "        if (_12) { \n"
      "          if (_13) { \n"
      "            if (_14) b = \"*\"; else b = \"8\"; \n"
      "          } else { \n"
      "            if (_14) b = \"(\"; else b = \"9\"; \n"
      "          } \n"
      "        } else { \n"
      "          if (_13) { \n"
      "            if (_14) b = \")\"; else b = \"0\"; \n"
      "          } else { \n"
      "            if (_14) b = \"_\"; else b = \"-\"; \n"
      "          } \n"
      "        } \n"
      "      } else { \n"
      "        if (_12) { \n"
      "          if (_13) { \n"
      "            if (_14) b = \"+\"; else b = \"=\"; \n"
      "          } else { \n"
      "            if (_14) b = \"{\"; else b = \"[\"; \n"
      "          } \n"
      "        } else { \n"
      "          if (_13) { \n"
      "            if (_14) b = \"}\"; else b = \"]\"; \n"
      "          } else { \n"
      "            if (_14) b = \":\"; else b = \";\"; \n"
      "          } \n"
      "        } \n"
      "      } \n"
      "    } \n"
      "    var c = \"\"; \n"
      "    if (_04) c = c + b; else c = c + a; \n"
      "    if (_03) c = c + b; else c = c + a; \n"
      "    if (_02) c = c + b; else c = c + a; \n"
      "    if (_01) c = c + b; else c = c + a; \n"
      "    if (_00) c = c + b; else c = c + a; \n"
      "    // print c; \n"
      "  } \n"
      "} \n";

  initVM(&vm, stdout, stderr);

  UBENCH_DO_BENCHMARK() {
    ires = interpret(&vm, src);
  }

  freeVM(&vm);
  assert(ires == INTERPRET_OK);
}

UBENCH_MAIN();
